# Image
FROM node:16

# create destination directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# update and install dependency
RUN apt update && apt upgrade -y && apt-get install -y nano

EXPOSE 3001
ENV NUXT_PORT=3001

# Configure host
ENV HOST 0.0.0.0

CMD [ "npm", "run", "dev" ]